### ISSUE TITLE
New Enemy: Koopa Troopa and Coin Tracker

### ISSUE THREAD

**Issue by i0nics** [i0nics/super-mario-run#3]
Koopa Troopas are turtle-like creatures. Similar to Goombas, the player needs to stomp on top of them to knock them out.

In order to implement more enemies, a new Enemy interface will be added that contain common functions such as Run() and checkPowerUp()

How Koopa Troopa Will Be Implemented:

A new Koopa Troopa class that implements Enemy needs to be created with a Run() method which primarily will move the Paratroopa's GImage left and right in air. An updateBounds() method will also be added so that two separate invisible GRectangles that surround the head and body are utilized to detect whether the player defeated the enemy or vice versa(). A checkPowerUp method will adjust the enemy's response according to the player's active power-up.

The existing Goomba class will also be updated so that it now implements the Enemy interface.

The speed of both enemies will also be dynamically obtained from a text file.

Coin tracker on top right will now track coins as player collects them

**Comment by i0nics** [comment]
@onzfonz @veasnaling

**Comment by onzfonz** [comment]
I think just have something in this instead with Koopa troopa and the Goomba for now. Have the speed and image be something that is stored in a file that could be accessed instead so that the enmy can be created dynamically from a text file. Let me know if you have any other questions 🚀

**Comment by i0nics** [comment]
@onzfonz Actually, I forgot about this but the location of pretty much everything at any level is already stored in a text file for dynamic level creation. Speed of the goombas normally vary based on player proximity but yeah adding the speed to the text file too should be quite doable. Also Goomba is already done and was pretty much the only enemy when we finished this in 2019.
